<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "excellencebilling": {
                            "component": "Excellence_Hello/js/view/billing-address",
                            "template" : "Excellence_Hello/view/billing-address"
                        }
                    }
                }
            }
        }
</script>


<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "excellencebilling": {
                            "component": "Excellence_Hello/js/view/shipping-method"
                        }
                    }
                }
            }
        }
</script>